default: cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/IGameBoard.java cpsc2150/connectX/GameBoard.java cpsc2150/connectX/GameBoardMem.java
	javac cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/IGameBoard.java cpsc2150/connectX/GameBoard.java cpsc2150/connectX/GameBoardMem.java

run: cpsc2150/connectX/Connect4Game.class cpsc2150/connectX/IGameBoard.class cpsc2150/connectX/GameBoard.class cpsc2150/connectX/GameBoardMem.class
	java cpsc2150/connectX/Connect4Game cpsc2150/connectX/IGameBoard cpsc2150/connectX/GameBoard cpsc2150/connectX/GameBoardMem

clean:
	rm -f cpsc2150/connectX/*.class

